### ISSUE TITLE
trouble compiling with msvc cpp 20

### ISSUE THREAD

**Issue by nickblock** [orosmatthew/nnm#1]
hello I found your lib on reddit and really like it!

I add your nnm.hpp file to my gtest cpp to try it out.

I get the following error:

nnm/nnm.hpp(4822,1): error C3538: in a declarator-list 'nnm::Matrix2' must always deduce to the same type [C:\Users\nick\Do
cuments\nnm\build\nnm_tests.vcxproj]
nnm/nnm.hpp(4822,1): message : could be 'nnm::Matrix2<float>' [build\nnm_tests.vcxproj]
nnm/nnm.hpp(4822,1): message : or       'nnm::Matrix3<float>' [build\nnm_tests.vcxproj]
nnm/nnm.hpp(4822,1): message : or       'nnm::Matrix4<float>' [build\nnm_tests.vcxproj]

so i download and build your test, it works. The problem though is that I set my cpp standard  to 20 (in CMakeLists), 

and I am running msvc. 

I do not see the error with your cpp 17. But simply set standard to 20 in your CMakeLists i see the error.

**Comment by orosmatthew** [comment]
This should now be fixed with commit b662612
